# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodingExercise
  pod 'Alamofire', '~> 5.4'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '~> 4.0'

  target 'CodingExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodingExerciseUITests' do
    # Pods for testing
  end

end
